FROM node:16.15.1

LABEL version="1.0"
LABEL description="This is the base docker image for Ouivalo backend API."
LABEL maintainer = ["matteogrellier@gmail.com"]

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]
RUN ls
RUN npm install --production
COPY . .

EXPOSE 5000

CMD ["node", "dist/index.js"]